name: myapp
description: MedTrix StudyOS - Secure Learning Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State & Navigation
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # UI Design
  dynamic_color: ^1.6.8
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  flutter_adaptive_scaffold: ^0.3.2

  # The Engine
  media_kit: ^1.1.0
  media_kit_video: ^1.2.0
  media_kit_libs_video: 1.0.0
  syncfusion_flutter_pdfviewer: ^32.1.19

  # Study Tools
  perfect_freehand: ^1.0.0
  wakelock_plus: ^1.1.0
  # auto_orientation: ^2.2.1
  screen_brightness: ^0.2.1

  # Database
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  device_info_plus: ^12.3.0

  # Network
  dio: ^5.4.1
  # workmanager: ^0.6.0
  background_downloader: ^8.2.0
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11
  isar_generator: 3.1.0+1

dependency_overrides:
  js: ^0.7.1

flutter:
  assets:
   - lib/assets/data/marrow_ordered.json
  uses-material-design: true
